### PR TITLE
Updates to readme

### PR DESCRIPTION
**Pull request by SachiraChin**
Added session link and books referred in the session. I think I'm can't write about what taught in the session because I'm very new to DDD and can't explain everything you said. Hope this small change would help you to add more details to it.

### CODE REVIEW

**Comment by SachiraChin** [comment]
Also, I tried to find `Domain Driven Design Patterns by Scott Millet`, but couldn't find it. I only found different book by him. I didn't add that book to the list because of that.

https://www.amazon.com/Patterns-Principles-Practices-Domain-Driven-Design/dp/1118714709

**Comment by adrianiftode** [comment]
I don't think Scott Millet has a different book that PPPDDD. Great book, btw

**Comment by julielerman** [comment]
i'll take this PR and then fix it up a littl eore with the book refs. Thanks for getting all that in there!

**Comment by SachiraChin** [comment]
No problem at all, glad it helped. 😊

**Pull request merged**
